# TCL File Generated by Component Editor 18.1
# Tue Feb 27 16:52:43 CET 2024
# DO NOT MODIFY


# 
# counter_avmm "Counter with Avalon Memory-Mapped Inerface" v1.4.1
# Yifeng Wang 2024.02.27.16:52:43
# see top file
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module counter_avmm
# 
set_module_property DESCRIPTION "Counter with sclr to monitor a given time window. Use avmm-read to retrieve the last value before the current sclr. Upper bit is the overflow flag, which is only reset upon reset. The sclr can be issued from outside as 1) reset_req or 2) internal generated based on settings or 3) avalon master write value '0'. "
set_module_property NAME counter_avmm
set_module_property VERSION 1.4.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Data Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "Counter with Avalon Memory-Mapped Inerface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL counter_avmm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file counter_avmm.vhd VHDL PATH counter_avmm.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N_COUNTER NATURAL 1
set_parameter_property N_COUNTER DISPLAY_NAME N_COUNTER
set_parameter_property N_COUNTER TYPE NATURAL
set_parameter_property N_COUNTER UNITS None
set_parameter_property N_COUNTER ALLOWED_RANGES 0:2147483647
set_parameter_property N_COUNTER HDL_PARAMETER true
add_parameter COUNTER_BITS NATURAL 31
set_parameter_property COUNTER_BITS DEFAULT_VALUE 31
set_parameter_property COUNTER_BITS DISPLAY_NAME COUNTER_BITS
set_parameter_property COUNTER_BITS TYPE NATURAL
set_parameter_property COUNTER_BITS UNITS None
set_parameter_property COUNTER_BITS ALLOWED_RANGES 0:2147483647
set_parameter_property COUNTER_BITS HDL_PARAMETER true

add_parameter USE_TOP_BIT_AS_OF_FLAG NATURAL 1
set_parameter_property USE_TOP_BIT_AS_OF_FLAG DEFAULT_VALUE 1
set_parameter_property USE_TOP_BIT_AS_OF_FLAG DISPLAY_NAME USE_TOP_BIT_AS_OF_FLAG
set_parameter_property USE_TOP_BIT_AS_OF_FLAG TYPE NATURAL
set_parameter_property USE_TOP_BIT_AS_OF_FLAG UNITS None
set_parameter_property USE_TOP_BIT_AS_OF_FLAG ALLOWED_RANGES 0:2147483647
set_parameter_property USE_TOP_BIT_AS_OF_FLAG HDL_PARAMETER true

add_parameter ADDR_W NATURAL 1
set_parameter_property ADDR_W DISPLAY_NAME ADDR_W
set_parameter_property ADDR_W TYPE NATURAL
set_parameter_property ADDR_W HDL_PARAMETER true

add_parameter READ_ON_THE_FLY BOOLEAN
set_parameter_property READ_ON_THE_FLY DISPLAY_NAME READ_ON_THE_FLY
set_parameter_property READ_ON_THE_FLY TYPE BOOLEAN
set_parameter_property READ_ON_THE_FLY HDL_PARAMETER true




#
# callback
#
set_module_property ELABORATION_CALLBACK elaborate

proc elaborate {} {
	set n_counter [get_parameter_value N_COUNTER]
	set width_address [expr round(ceil(log($n_counter)/log(2)))]
	
	
	
	
	if {$n_counter == 1} {
		set_port_property avs_cntval_address termination true
		set_port_property avs_cntval_address termination_value 0
		send_message INFO "{Callback}: Disable address of AVMM port to shrink memory space usage during assigning base address"
	} else {
		set_port_property avs_cntval_address WIDTH_EXPR $width_address
		
		send_message INFO [format "{Callback}: Set the address of AVMM to (%s), according to the N_COUNTER" $width_address]
	}
	
}


# 
# display items
# 


# 
# connection point avmm_counter_value
# 
add_interface avmm_counter_value avalon end
set_interface_property avmm_counter_value addressUnits WORDS
set_interface_property avmm_counter_value associatedClock clock_sink
set_interface_property avmm_counter_value associatedReset reset_sink
set_interface_property avmm_counter_value bitsPerSymbol 8
set_interface_property avmm_counter_value burstOnBurstBoundariesOnly false
set_interface_property avmm_counter_value burstcountUnits WORDS
set_interface_property avmm_counter_value explicitAddressSpan 0
set_interface_property avmm_counter_value holdTime 0
set_interface_property avmm_counter_value linewrapBursts false
set_interface_property avmm_counter_value maximumPendingReadTransactions 0
set_interface_property avmm_counter_value maximumPendingWriteTransactions 0
set_interface_property avmm_counter_value readLatency 0
set_interface_property avmm_counter_value readWaitTime 1
set_interface_property avmm_counter_value setupTime 0
set_interface_property avmm_counter_value timingUnits Cycles
set_interface_property avmm_counter_value writeWaitTime 0
set_interface_property avmm_counter_value ENABLED true
set_interface_property avmm_counter_value EXPORT_OF ""
set_interface_property avmm_counter_value PORT_NAME_MAP ""
set_interface_property avmm_counter_value CMSIS_SVD_VARIABLES ""
set_interface_property avmm_counter_value SVD_ADDRESS_GROUP ""

add_interface_port avmm_counter_value avs_cntval_readdata readdata Output counter_bits+use_top_bit_as_of_flag
add_interface_port avmm_counter_value avs_cntval_read read Input 1
add_interface_port avmm_counter_value avs_cntval_address address Input 1
add_interface_port avmm_counter_value avs_cntval_waitrequest waitrequest Output 1
add_interface_port avmm_counter_value avs_cntval_writedata writedata Input 32
add_interface_port avmm_counter_value avs_cntval_write write Input 1

set_interface_assignment avmm_counter_value embeddedsw.configuration.isFlash 0
set_interface_assignment avmm_counter_value embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmm_counter_value embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmm_counter_value embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink i_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink i_rst reset Input 1


# 
# connection point counter_control_port
# 
add_interface counter_control_port conduit end
set_interface_property counter_control_port associatedClock clock_sink
set_interface_property counter_control_port associatedReset reset_sink
set_interface_property counter_control_port ENABLED true
set_interface_property counter_control_port EXPORT_OF ""
set_interface_property counter_control_port PORT_NAME_MAP ""
set_interface_property counter_control_port CMSIS_SVD_VARIABLES ""
set_interface_property counter_control_port SVD_ADDRESS_GROUP ""

add_interface_port counter_control_port counter_en enable Input n_counter
add_interface_port counter_control_port counter_sclr sclr Input 1

